language: python
dist: xenial

matrix:
  include:
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8

install:
  - pip install pycodestyle pyflakes mypy coveralls pandas sympy
  - pip install pytest pytest-cov altair matplotlib mkdocs
  - pip install holoviews, bokeh
  - pip install -e .

before_script:
  - pycodestyle pheasant
  - pyflakes pheasant
   - mypy pheasant
  - pycodestyle tests
  - pyflakes tests

script:
  - pytest

after_success:
  - coveralls
