language: python
python:
  - "3.6"

before_install:
  # - sudo apt-get install julia

install:
  - pip install click jupyter coveralls pytest-cov coverage
  - pip install flake8 mkdocs pelican matplotlib pandas bokeh
  - pip install -e .
  # - which jupyter
  # - julia -e 'Pkg.build("IJulia")'

before_script:
  - flake8 pheasant

script:
  - jupyter kernelspec list
  - pheasant --version
  - pytest

after_success:
  - coveralls
