language: python
python:
  - "3.6"

before_install:
  # - sudo apt-get install julia

install:
  - pip install click jupyter coveralls pytest-cov coverage
  - pip install flake8 mkdocs pelican
  - pip install -e .
  # - which jupyter
  # - julia -e 'Pkg.build("IJulia")'

before_script:
  - flake8 pheasant

script:
  - jupyter kernelspec list
  - pheasant --version
  # - pheasant kernelname
  - pytest
  # - pheasant convert tests/resources/mkdocs/docs/markdown_stream_input.md
  # - pheasant convert tests/resources/mkdocs/docs/notebook_stream_input.ipynb

after_success:
  - coveralls
