language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install click jupyter coveralls pytest-cov coverage holoviews
  - pip install flake8 mkdocs pelican matplotlib pandas bokeh sympy
  - pip install selenium
  - pip install -e .

before_script:
  - flake8 pheasant
  - python -m ipykernel install --user --name travis
  - julia

script:
  - jupyter kernelspec list
  - pytest

after_success:
  - coveralls
