language: python
dist: xenial

matrix:
  include:
    - os: linux
      python: 3.7

install:
  - pip install pycodestyle pyflakes mypy coveralls
  - pip install -e .

before_script:
  - pycodestyle pheasant
  - pyflakes pheasant
  # - mypy pheasant
  - pycodestyle tests
  - pyflakes tests

script:
  - python setup.py test

after_success:
  - coveralls
