language: python
dist: xenial

matrix:
  include:
    - os: linux
      python: 3.7

install:
  - npm install -g ijavascript
  - pip install pycodestyle pyflakes mypy
  - pip install pytest-cov coveralls
  - pip install -e .[develop]

before_script:
  - pycodestyle pheasant
  - pyflakes pheasant
  - mypy pheasant
  - pycodestyle tests
  - pyflakes tests
  - python -m ipykernel install --user --name travis

script:
  - jupyter kernelspec list
  - pytest

after_success:
  - coveralls
