language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install click jupyter coveralls pytest-cov coverage
  - pip install flake8 mkdocs pelican matplotlib pandas bokeh
  - pip install -e .

before_script:
  - flake8 pheasant

script:
  - jupyter kernelspec list
  - pytest

after_success:
  - coveralls
