language: python
python:
  - "3.6"

before_install:
  # - sudo apt-get install julia

install:
  - pip install click jupyter coveralls pytest-cov coverage
  - pip install flake8 mkdocs pelican matplotlib pandas bokeh
  - pip install -e .
  # - which jupyter
  # - julia -e 'Pkg.build("IJulia")'

before_script:
  - flake8 pheasant
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
    fi

script:
  - jupyter kernelspec list
  - pheasant --version
  - pytest

after_success:
  - coveralls
