language: python
dist: xenial

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7

install:
  - pip install coveralls pytest-cov coverage  # for py3.6
  - pip install -e .[develop]

before_script:
  - pycodestyle pheasant
  - flake8 pheasant
  - mypy pheasant
  - python -m ipykernel install --user --name travis

script:
  - jupyter kernelspec list
  - pytest

after_success:
  - coveralls
