language: python
dist: xenial

matrix:
  include:
    - os: linux
      python: 3.7

install:
  - pip install pycodestyle pyflakes mypy coveralls pandas sympy
  - pip install bokeh==1.4.0
  - pip install pytest pytest-cov altair holoviews matplotlib mkdocs
  - pip install -e .

before_script:
  - pycodestyle pheasant
  - pyflakes pheasant
  # - mypy pheasant
  - pycodestyle tests
  - pyflakes tests

script:
  - pytest

after_success:
  - coveralls
