build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=%PYTHON_VERSION%
  - activate test-environment
  - pip install pandas sympy
  - pip install bokeh==1.4.0
  - pip install pytest pytest-cov altair holoviews matplotlib mkdocs
  - pip install -e .

test_script:
  - pytest
