# Jinja2 template file for numbering.
header_template_file: header.jinja2
anchor_template_file: anchor.jinja2
# List of numbered objects
kind:
  - header
  - figure
  - table
  - code
  - file
# Numbering level. 0 for multiple pages 2 for h2 etc.
level: 0
# Begin pattern
begin_pattern: <!-- begin -->
# End pattern
end_pattern: <!-- end -->
# <div> class name for numbered objects.
class: pheasant-header-{kind}
# <div> id name for numbered objects.
id: pheasant-header-{tag}
# relpath function
relpath_function: null
