site_name: Pheasant
site_url: https://pheasant.daizutabi.net/
repo_url: https://github.com/daizutabi/pheasant/
repo_url: https://github.com/daizutabi/pheasant/

theme:
  name: readthedocs

extra:
  search:
    language: 'en'

extra_css:
  - css/pheasant.css

markdown_extensions:
  - admonition
  - pymdownx.arithmatex

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

plugins:
  - pheasant:
      jupyter:
        output_format: markdown
        kernel_name: {'python': 'python3'}
        enabled: True
      number:
        enabled: True
      debug:
        enabled: False

pages:
  - Home: index.md
  - Markdown Stream: markdown_stream_input.md
  - Notebook Stream: notebook_stream_input.ipynb
  - Markdown Display: display/markdown_display_input.md
  - Notebook Display: notebook_display_input.ipynb
