site_name: Pheasant
site_url: https://pheasant.daizutabi.net/
site_description: Project documentation with MkDocs.
site_author: daizutabi

repo_url: https://github.com/daizutabi/pheasant/
edit_uri: ""

theme:
    name: readthedocs
    hljs_languages:
      - yaml
    custom_dir: custom_theme/

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js

plugins:
  - pheasant:

nav:
  - Home: index.md
  - User Guide:
    - Images: user-guide/images.md
    - Embed: user-guide/embed.md
    - SymPy: user-guide/sympy.md
    - Script: user-guide/script.py
  - About:
    - Release Notes: about/release-notes.md
    - License: about/license.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
