site_name: Pheasant
site_url: https://pheasant.daizutabi.net/
site_description: Project documentation with MkDocs.
site_author: daizutabi

repo_url: https://github.com/daizutabi/pheasant/
edit_uri: ""

theme: readthedocs

plugins:
  - pheasant:

nav:
  - Home: index.md
  - User Guide:
    - Images: user-guide/images.md
    - Code: user-guide/code.md
    - Script: user-guide/script.py
  - About:
    - Release Notes: about/release-notes.md
    - License: about/license.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
#   - attr_list
